mysite/mysite/urls.py
# from django.contrib import admin
#
# from django.urls import include, path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('polls/',include('polls.url')),
# ]

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include(('polls.urls','polls'),namespace='polls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
# from django.contrib import admin
# from django.conf.urls import include
# from django.urls import path
# from . import views
#
#
# urlpatterns = [
#     path('', views.index, name="index"),
#     # 127.0.0.1/polls/
# ]

# from django.urls import path
#
# from . import views
#
#
# urlpatterns = [
#     path('', views.index, name='index'),
#     # 127.0.0.1/polls/
# ]

from django.urls import path

from . import views

urlpatterns = [
    # ex: /polls/
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

mysite/polls/models.py
from django.db import models


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    no_of_votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete = models.CASCADE)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render,get_object_or_404

from django.template import loader, RequestContext
# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect

from .models import Question,Choice
from django.urls import reverse

def index(request):
    # return HttpResponse('good job!,this is the index page of the polls app')

    # latest_question= Question.objects.order_by('pub_date')[:5]
    # output= ','.join(q.question_text for q in latest_question)
    # return HttpResponse(output)

    # latest_question = Question.objects.order_by('-pub_date')[:5]
    # template = loader.get_template('polls/index.html')
    # context = {
    #     'latest_question': latest_question,
    # }
    # return HttpResponse(template.render(context, request))

    latest_question = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question': latest_question}
    return render(request, 'polls/index.html', context)


def detail(request, question_id):
    # return HttpResponse("You're looking at question %s." % question_id)
    # question=Question.objects.get(pk=question_id)
    question = get_object_or_404(Question,pk=question_id)
    context = {'question': question}
    return render(request, 'polls/detail.html', context)

def results(request, question_id):
    # response = "You're looking at the results of question %s."
    # return HttpResponse(response % question_id)
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'polls/result.html', context)


def vote(request, question_id):
    # return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question,pk=question_id)

    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.no_of_votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/base.html
{% load static %}


<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.1.1">

    <title>POLLS</title>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/bootstrap-4.5.3-dist/css/bootstrap.min.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>
<body>
{% include "polls/header.html" %}
<div class="jumbotron">
<div class="container">

    {% block main_content %}
    {% endblock %}
    {% include "polls/footer.html" %}
</div>
</div>

</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block main_content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" class="btn btn-success" value="Vote">
</form>
<a href="{% url 'polls:index'  %}"> BACK TO QUESTIONS</a>

{% endblock %}


<!--<ul>-->
<!--    {% for choice in question.choice_set.all %}-->
<!--        <li>{{ choice.choice_text }}</li>-->
<!--    {% endfor %}-->
<!--</ul>-->

mysite/polls/templates/polls/footer.html
<footer class="container">
  <p>&copy; SHANI and RAJARAJESHWARI Company 2017-2020</p>
</footer>

mysite/polls/templates/polls/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Jashwanth Dream11</a>
<!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->

<!--  <div class="collapse navbar-collapse" id="navbarsExampleDefault">-->
<!--    <ul class="navbar-nav mr-auto">-->
<!--      <li class="nav-item active">-->
<!--        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link" href="#">Link</a>-->
<!--      </li>-->
<!--      <li class="nav-item">-->
<!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--      </li>-->
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>-->
<!--        <div class="dropdown-menu" aria-labelledby="dropdown01">-->
<!--          <a class="dropdown-item" href="#">Action</a>-->
<!--          <a class="dropdown-item" href="#">Another action</a>-->
<!--          <a class="dropdown-item" href="#">Something else here</a>-->
<!--        </div>-->
<!--      </li>-->
<!--    </ul>-->
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

mysite/polls/templates/polls/index.html
{% extends 'polls/base.html' %}

{% block main_content %}

<h1> Choose a Question</h1>
<!--{% if latest_question%}-->
<!--    <ol>-->
<!--        {% for question in latest_question %}-->
<!--          <li><a href="/polls/{{question_id}}"><br>{{question.question_text}}</br></a></li>-->
<!--        {% endfor %}-->
<!--    </ol>-->
<!--{% else %}-->
<!--     <p>no more questions fo u,nedded u can add some</p>-->
<!--{% endif %}-->

{% if latest_question %}
    <ul>
    {% for question in latest_question %}
<!--        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

mysite/polls/templates/polls/result.html
{% extends 'polls/base.html' %}
{% block main_content %}

<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{choice.no_of_votes}} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>


<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

{% endblock %}